name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
prerelease: true
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels:
      - 'new-feature'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🎨 CSS'
    labels:
      - 'css'
  - title: '☕️ JavaScript'
    labels:
      - 'js'
  - title: '📖 Docs'
    labels:
      - 'docs'
  - title: '🌎 Accessibility'
    labels:
      - 'accessibility'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
  - title: '🧰 Misc'
    labels:
      - 'build'
      - 'meta'
      - 'chore'
change-template: '- #$NUMBER: $TITLE'
template: |
  ## Changes
  $CHANGES
